---
title: "2d_tests"
author: "Vincent Runge"
date: "13 avril 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Installation of the package from github
```{r}
#devtools::install_github("vrunge/nnlm")
library(nnlm)
```
## Data generation

We chose parameters: columns X1 and X2

```{r}
nbSimu <- 10^5
n <- 500
sigma <- 1
X1 <- runif(n, min=0, max = 1)
X2 <- runif(n, min=0, max = 4)
X1 <- sample(c(0,1), n, replace = TRUE)
X2 <- sample(c(0,1), n, replace = TRUE)

#X1 <- rnorm(n)
#X2 <- rnorm(n)
#X1 <- runif(n, min=0, max = 1)
#X2 <- runif(n, min=0, max = 1)

```

## Proba estimation


```{r}
#X1 <- X1 - mean(X1)
#X2 <- X2 - mean(X2)

p <- probaEstimation(X1, X2, sigma, n, nbSimu = nbSimu)
p
```


## Comparison simulation VS estimator 

```{r}
step <- 0.001
h <- densitybeta1(X1, X2, sigma, p, h = step, max = 30)
b1 <- beta1estimator0(X1, X2, sigma, n, nbSimu = nbSimu)
```


## Plots and tests

```{r}
his <- hist(b1$beta1[b1$beta1>0], breaks = 50, probability = TRUE, ylab = "", xlab = "", main = "")
par(new=TRUE)
plot(h$x,h$y/sum(step*h$y), type = 'l', xlim = c(0,max(his$breaks)), ylim = c(0, his$density[1]), ylab = "", xlab = "", main = "beta1 density in 2d case")


#verif density = 1
his$density%*%diff(his$breaks)
sum(step*h$y) + h$d0

#comparaison dirac en 0
sum(b1$beta1 == 0)/nbSimu
p[2] + p[3]
```



```{r}
X1carre <- c(X1%*%X1)
X2carre <- c(X2%*%X2)
X12 <- c(X1%*%X2)
Delta <- X1carre*X2carre - X12^2
X12
sqrt(X2carre/Delta)
p[1]
1/sqrt(X1carre)
p[4]
```



## Variables A1 and A2 : distributions


```{r}
hist(b1$A, breaks = 50, probability = TRUE, col = 2)
hist(b1$B, breaks = 50, probability = TRUE, col = 3)
```


```{r}
library(stats)
shapiro.test(sample(c(b1$A,-b1$A), 5000))
shapiro.test(sample(c(b1$B,-b1$B), 5000))
shapiro.test(sample(c(b1$A,-b1$A,b1$B,-b1$B), 5000))
```

